version: '3'

services:
  app:
    depends_on:
      - pg-master
      - pg-slave
    image: np-addons-demo-r2:0.0.1-SNAPSHOT
    volumes:
      - ./np-addons-demo-r2:/opt/np-addons-demo-r2-home
    ports:
      - "8080:8080"
  pg-master:
    build: ./postgres/master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=r2demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PG_REP_USER=replicator
      - PG_REP_PASSWORD=replicator
    ports:
    - "5433:5432"
  pg-slave:
    build: ./postgres/slave
    depends_on:
      - pg-master
    environment:
      - POSTGRES_DB=r2demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PG_REP_USER=replicator
      - PG_REP_PASSWORD=replicator
      - PG_MASTER_HOST=pg-master
    ports:
      - "5434:5432"
volumes:
  pg_data: