
CREATE TABLE owner
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    city       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255),
    telephone  VARCHAR(255),
    CONSTRAINT pk_owner PRIMARY KEY (id)
);